name: Download ZIPs

on:
  push:
    paths:
      - 'zip_links.txt'   # 仅当 zip_links.txt 被推送时触发
  workflow_dispatch:       # 也允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run downloader
        run: python download.py

      - name: Upload downloaded ZIPs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-zips
          path: downloads/
          retention-days: 30   # 按需调整保留天数