name: Download ZIPs

on:
  push:
    paths:
      - 'zip_links.txt'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run downloader & pack
        run: python download.py

      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: zip-bundles
          path: bundles/
          retention-days: 30