name: Download ZIPs

on:
  push:
    paths:
      - 'zip_links.txt'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run parallel downloader
        run: python download.py        # 默认线程数 = CPU 核心 * 5

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-zips
          path: downloads/
          retention-days: 30